/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WisdomRouteImport } from './routes/wisdom'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as IncentivesRouteImport } from './routes/incentives'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const WisdomRoute = WisdomRouteImport.update({
  id: '/wisdom',
  path: '/wisdom',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const IncentivesRoute = IncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/communities': typeof CommunitiesRoute
  '/graph': typeof GraphRoute
  '/incentives': typeof IncentivesRoute
  '/ledger': typeof LedgerRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wisdom': typeof WisdomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/communities': typeof CommunitiesRoute
  '/graph': typeof GraphRoute
  '/incentives': typeof IncentivesRoute
  '/ledger': typeof LedgerRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wisdom': typeof WisdomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/communities': typeof CommunitiesRoute
  '/graph': typeof GraphRoute
  '/incentives': typeof IncentivesRoute
  '/ledger': typeof LedgerRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wisdom': typeof WisdomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/communities'
    | '/graph'
    | '/incentives'
    | '/ledger'
    | '/missions'
    | '/settings'
    | '/sitemap.xml'
    | '/wisdom'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/communities'
    | '/graph'
    | '/incentives'
    | '/ledger'
    | '/missions'
    | '/settings'
    | '/sitemap.xml'
    | '/wisdom'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/communities'
    | '/graph'
    | '/incentives'
    | '/ledger'
    | '/missions'
    | '/settings'
    | '/sitemap.xml'
    | '/wisdom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CommunitiesRoute: typeof CommunitiesRoute
  GraphRoute: typeof GraphRoute
  IncentivesRoute: typeof IncentivesRoute
  LedgerRoute: typeof LedgerRoute
  MissionsRoute: typeof MissionsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WisdomRoute: typeof WisdomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wisdom': {
      id: '/wisdom'
      path: '/wisdom'
      fullPath: '/wisdom'
      preLoaderRoute: typeof WisdomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incentives': {
      id: '/incentives'
      path: '/incentives'
      fullPath: '/incentives'
      preLoaderRoute: typeof IncentivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CommunitiesRoute: CommunitiesRoute,
  GraphRoute: GraphRoute,
  IncentivesRoute: IncentivesRoute,
  LedgerRoute: LedgerRoute,
  MissionsRoute: MissionsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WisdomRoute: WisdomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
