/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WisdomRouteImport } from './routes/wisdom'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as IndexRouteImport } from './routes/index'

const WisdomRoute = WisdomRouteImport.update({
  id: '/wisdom',
  path: '/wisdom',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/missions': typeof MissionsRoute
  '/wisdom': typeof WisdomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/missions': typeof MissionsRoute
  '/wisdom': typeof WisdomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/missions': typeof MissionsRoute
  '/wisdom': typeof WisdomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/missions' | '/wisdom'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/missions' | '/wisdom'
  id: '__root__' | '/' | '/missions' | '/wisdom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MissionsRoute: typeof MissionsRoute
  WisdomRoute: typeof WisdomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wisdom': {
      id: '/wisdom'
      path: '/wisdom'
      fullPath: '/wisdom'
      preLoaderRoute: typeof WisdomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MissionsRoute: MissionsRoute,
  WisdomRoute: WisdomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
